site_name: Mon Portfolio
theme:
  name: material
  palette:
    primary: teal
    accent: deep orange
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

repo_url: https://github.com/Esteban-Mo/Portoflio-MKDOCS
repo_name: Esteban-Mo/Portoflio-MKDOCS

nav:
  - Accueil: index.md
  - Projets: projets.md
  - À propos: about.md
  - Contact: contact.md